#! /bin/sh

export PATH=$PATH:~/.bin

bspc config border_width 7
bspc config window_gap 12
bspc config top_padding	16
bspc config focused_border_color "#EEEEEE"
bspc config normal_borber-color "#2D2D2D"

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc monitor -d o o o o o o o

bspc rule -a Gimp follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a Firefox desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Conky floating=on focus=off
bspc rule -a feh floating=on
bspc rule -a vlc floating=on
bspc rule -a mpv floating=on

panel &
compton &
termite &
xsetroot -cursor_name left_ptr
feh --bg-scale ~/usr/img/Wallpapers/fp0Jtgr.jpg
redshift &
sxhkd &
